### ISSUE TITLE
Terraform is trying to poll Master node before creation

### ISSUE THREAD

**Issue by RicardoDMAraujo** [fvumbaca/terraform-proxmox-k3s#1]
Hey there 👋 

Just stumbled on your module and thought it was interesting.
Found an issue where you are polling the master VM for the kubeconfig before it's creation.

Fixed it by adding a 
`    depends_on = [
      proxmox_vm_qemu.k3s-master,
    ]
`
block here https://github.com/fvumbaca/terraform-proxmox-k3s/blob/main/master_nodes.tf#L93

Have a great day

**Comment by fvumbaca** [comment]
Hey! Thanks for the issue! This should now be fixed in [v0.0.3](https://github.com/fvumbaca/terraform-proxmox-k3s/releases/tag/v0.0.3). Hope your enjoying the module! 🙂
