### ISSUE TITLE
Error: 500 storage 'local-lvm' is not available on node

### ISSUE THREAD

**Issue by OvrAp3x** [fvumbaca/terraform-proxmox-k3s#2]
Getting this error when creating, I do not have the storage local-lvm in proxmox as it is installed on zfs.
Is it possible to add a option to modify this in a setting?
"master_node_storage=USERSPECIFIED"
"support_node_storage=USERSPECIFIED"

?

**Comment by fvumbaca** [comment]
Yeah I should be able to get around to that later today. Thanks for the issue!

**Comment by fvumbaca** [comment]
The option to specify the storage type and id are now available in [v0.1.0](https://github.com/fvumbaca/terraform-proxmox-k3s/releases/tag/v0.1.0). Feel free to re-open the issue if this did not solve your problem.

**Comment by OvrAp3x** [comment]
Great!
Thank you very much🙂🔥
