### ISSUE TITLE
Missing required argument - pm_api_url

### ISSUE THREAD

**Issue by michalstrelec** [fvumbaca/terraform-proxmox-k3s#4]
I have tried to execute 'terraform plan' and the following error is displayed:

│ Error: Missing required argument
│ 
│ The argument "pm_api_url" is required, but was not set.

Is this something that needs to be added as an configuration item in main.tf?

**Comment by mannp** [comment]
It took me some time to figure this out too 👍🏻

**Comment by theautomation** [comment]
Me to. Maybe you can add this to the readme :)
