### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by niukekkk** [fvumbaca/terraform-proxmox-k3s#8]
(base) [root@localhost terraform-proxmox-k3s]# terraform plan
var.authorized_keys_file
  Path to file containing public SSH keys for remoting into nodes.

  Enter a value: /root/.ssh/authorized_keys

var.control_plane_subnet
  Enter a value: 192.168.0.200/29

var.lan_subnet
  Subnet used by the LAN network. Note that only the bit count number at the end
  is acutally used, and all other subnets provided are secondary subnets.

  Enter a value: 192.168.0.0/16

var.master_node_settings
  Enter a value: 

var.network_gateway
  IP address of the network gateway.

  Enter a value: 192.168.0.1

var.node_pools
  Node pool definitions for the cluster.

  Enter a value: name = "default",size = 2,subnet = "192.168.0.208/28"

var.node_template
  Proxmox vm to use as a base template for all nodes. Can be a template or
  another vm that supports cloud-init.

  Enter a value: Ubuntu18.04

var.proxmox_node
  Proxmox node to create VMs on.

  Enter a value: pve1

var.support_node_settings
  Enter a value: 

╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on versions.tf line 14, in terraform:
│   14:   experiments = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
╵
╷
│ Error: Missing expression
│ 
│   on <value for var.master_node_settings> line 1:
│   (source code not available)
│ 
│ Expected the start of an expression, but found the end of the file.
╵
╷
│ Error: Extra characters after expression
│ 
│   on <value for var.node_pools> line 1:
│   (source code not available)
│ 
│ An expression was successfully parsed, but extra characters were found after it.
╵
╷
│ Error: Missing expression
│ 
│   on <value for var.support_node_settings> line 1:
│   (source code not available)
│ 
│ Expected the start of an expression, but found the end of the file.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 63:
│   63: variable "support_node_settings" {
│ 
│ The root module input variable "support_node_settings" is not set, and has no default value. Use a -var or -var-file command line argument to provide a value for this variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 83:
│   83: variable "master_node_settings" {
│ 
│ The root module input variable "master_node_settings" is not set, and has no default value. Use a -var or -var-file command line argument to provide a value for this variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 95:
│   95: variable "node_pools" {
│ 
│ The root module input variable "node_pools" is not set, and has no default value. Use a -var or -var-file command line argument to provide a value for this variable.
╵
--------

**Comment by niukekkk** [comment]
Can you provide a sample implementation

**Comment by fvumbaca** [comment]
Hey @niukekkk thanks for giving this module a try!

I wrote a quick example project with a README to walk you through the process in the linked MR above. Give it a look to see if it helps you deploy your cluster! Feel free to leave comments on the MR if there is something that did not go well for you and I can clarify it.

Let me know when your issue is resolved so we can close this issue and merge the example to master!
